Added ability to load prototypes recursively
MrGVSV/bevy_proto pull request #6
Opened 2022-01-10 19:41 UTC by edouardpoitras

Not sure this PR is the cleanest way of doing it, but I needed that capability and it works on my end.
Please provide feedback and request changes as needed.

2022-01-10 19:50 UTC, edouardpoitras commented
A few things maybe worth discussing:
1) Should we put a recursive depth limit?
2) I didn't bump the version - maybe worth going to 0.2.1?
3) A better/cleaner approach that I didn't think of?
4) Adding a parameter to with_dir/with_dirs instead of the two new variants with_dir_recursive/with_dirs_recursive? This means breaking backwards compatibility.

2022-01-11 20:45 UTC, MrGVSV requested changes
Looks good to me (just a few suggestions). Thanks for this!

2022-01-11 20:45 UTC, MrGVSV commented on src/data.rs
> +	///		recursive_loading: true,
```suggestion
	///	recursive_loading: true,
```

2022-01-11 20:45 UTC, MrGVSV commented on src/plugin.rs
> +	/// Same as with_dir but recursively loads prototype files.
Would be better to link this directly to the method so it's easier to find.

```suggestion
	/// Same as [with_dir] but recursively loads prototype files.
```

2022-01-11 20:45 UTC, MrGVSV commented on src/plugin.rs
> +	/// Same as with_dirs but recursively loads prototype files.
```suggestion
	/// Same as [with_dirs] but recursively loads prototype files.
```

2022-01-11 20:53 UTC, MrGVSV commented
> 1. Should we put a recursive depth limit?

I don't think so. It could result in undefined behavior (unless we allow them to set the limit themselves, in which case, `recursive_loading` should probably be replaced with an `Option<u8>`).


> 2. I didn't bump the version - maybe worth going to 0.2.1?

Yeah, I'll bump and publish. Hoping to work on a version 0.3 release for Bevy 0.6 soon.


> 3. A better/cleaner approach that I didn't think of?

I find this approach pretty clean myself. If you want to add the recursion limit, that would be nice as well, but not super necessary at the moment.


> 4. Adding a parameter to with_dir/with_dirs instead of the two new variants with_dir_recursive/with_dirs_recursive? This would mean breaking backwards compatibility though.

I'm okay with the methods. I'd rather not add parameters to the others if we can help it (especially if those values are always typically going to be `true` or `false`, depending on the user's preference).

2022-01-12 00:36 UTC, edouardpoitras commented
Great! Thanks.

2022-01-12 00:48 UTC, MrGVSV approved these changes
Awesome, thanks! I'll try to get a new version published sometime tonight or tomorrow.

2022-01-13 06:32 UTC, merged